
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int AND = 21;
  public static final int NE = 18;
  public static final int LT = 13;
  public static final int ELSE = 3;
  public static final int TRUTH = 33;
  public static final int PLUS = 9;
  public static final int OR = 20;
  public static final int INT = 5;
  public static final int SEMI = 23;
  public static final int WHILE = 8;
  public static final int RSB = 28;
  public static final int RETURN = 6;
  public static final int IF = 4;
  public static final int GT = 15;
  public static final int ID = 31;
  public static final int LE = 14;
  public static final int TILDE = 19;
  public static final int NUM = 32;
  public static final int LCB = 29;
  public static final int LB = 25;
  public static final int RB = 26;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int GE = 16;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int FWDSLASH = 12;
  public static final int RCB = 30;
  public static final int EQ = 22;
  public static final int BOOL = 2;
  public static final int EQEQ = 17;
  public static final int LSB = 27;
  public static final int VOID = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "FWDSLASH",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQEQ",
  "NE",
  "TILDE",
  "OR",
  "AND",
  "EQ",
  "SEMI",
  "COMMA",
  "LB",
  "RB",
  "LSB",
  "RSB",
  "LCB",
  "RCB",
  "ID",
  "NUM",
  "TRUTH"
  };
}

